[package]
name = "sci-rs"
version = "0.1.0"
edition = "2021"
authors = ["Matthew R. Hennefarth"]

[dependencies]
num-traits = "0.2"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "docs-header.html" ]
